### ISSUE TITLE
Ability to uncall zoom behavior

### ISSUE THREAD

**Issue by pkerpedjiev** [d3/d3-zoom#104]
Calling the zoom behavior on a selection sets up a number of event listeners which catch and respond to various events. It would be nice if there was an API for undoing this action and removing all of the event listeners.

Currently, as far as I can tell, there's two ways to accomplish this:

1. Remove the element on which the zoom behavior was called.
2. Manually remove all of the event handlers:

```
selection
	.on("wheel.zoom", null)
  	.on("mousedown.zoom", null)
  	.on("dblclick.zoom", null)
  	.on("touchstart.zoom", null)
  	.on("touchmove.zoom", null)
  	.on("touchend.zoom touchcancel.zoom", null)
```

Would it make sense to have something like:

```
zoom.uncall(selection)
```

Which reverses the effect of `zoom.call`?

This would be useful in cases where the zoom behavior needs to be turned off. In my case, for example, I want to temporarily disable zooming when somebody is scrolling through a page. I do this by catching scroll events and disabling the zoom behavior for 50ms before re-enabling it. This means lots of additions and removals of the zoom behavior and its associated event listeners. The API for adding it is there but the API for removing it doesn't seem to be.

**Comment by mbostock** [comment]
Per the README, the recommended way to unbind the zoom behavior is:

```js
selection.on(".zoom", null);
```

**Comment by pkerpedjiev** [comment]
You're right. Sorry about that.

I had been trying to do `behavior.on('zoom', null)`.
