### ISSUE TITLE
iOS Safari bug when toggling between multiple states

### ISSUE THREAD

**Issue by ekeric13** [d3/d3-zoom#116]
I have a click handler that toggles on and off multiple zoom behaviors.
```
clickHandler(){
  if (state1Selected){
      d3CanvasSelector.call(zoomBehavior2).on('.zoom .start .end', null)
      d3CanvasSelector.call(zoomBehavior1);
  } else if ( state2Selected) {
      d3CanvasSelector.call(zoomBehavior1).on('.zoom .start .end', null)
      d3CanvasSelector.call(zoomBehavior2);
   } else {
       d3CanvasSelector.on('.zoom .start .end', null)
   }
}
```

It works as expected on chrome and safari. But it ends up breaking in iOS safari after this sequence of events.
state1Selected - drag and zoom work fine
state2Selected - drag and zoom work fine
state1Selected - when trying to drag, transform.k is getting increased/decreased. behavior breaks down.

Will try to replicate in a open source environment when I get the time.

**Comment by mbostock** [comment]
Closing to inactivity.
