### ISSUE TITLE
Edge/IE canvas pan and zoom looks "choppy"

### ISSUE THREAD

**Issue by rssfrncs** [d3/d3-zoom#128]
1. Load https://bl.ocks.org/mbostock/d1f7b58631e71fbf9c568345ee04a60e in MS Edge or IE 11.
2. Pan and zoom the page
3. Load https://bl.ocks.org/mbostock/d1f7b58631e71fbf9c568345ee04a60e in Chrome
5. Observe the difference in rendering, Edge and IE interaction seems to block rendering

Is this a known issue with MS browsers? The difference is shocking.

**Comment by rssfrncs** [comment]
Runs smoother on my mobile (Xiaomi A1) chrome again though.

**Comment by mbostock** [comment]
Not much I can do about rendering performance across browsers.
