### ISSUE TITLE
Zoom with ScaleBand

### ISSUE THREAD

**Issue by SnehaSSD** [d3/d3-zoom#134]
Hi,

I am currently using d3 v4. My x scale is a scaleBand where i am taking country name for the display and my y scale is scaleTime. When i am trying to get new xScale in zoom function its throwing error at rescaleX . I looked at many examples online but all of them either have a linerScale or scaleTime. 

```
var countryArr = ["USA", "UK", "Poland", "Sweden"];
var firstDay = moment(day).subtract(1, 'days').toDate();
var lastDay = moment(day).add(1, 'days').toDate();

// define scale
var yScale = d3.scaleTime().range([0, width]); 
yScale.domain([firstDay, lastDay]);
var xScale = d3.scaleBand().range([0, height]);
xScale.domain(countryArr);

// define zoom
var zoom = d3.zoom()
    .scaleExtent([1, 1])
    .translateExtent([[margin.left, margin.top], [width, height]])
    .on("zoom", zoomed);

d3.select("#main-canvas").call(zoom);

function zoomed() {
    //console.log(d3.event.transform.y);
    var new_x = d3.event.transform.rescaleX(xScale);  // ERROR at this line
    var new_y = d3.event.transform.rescaleY(yScale); 
}
```

<img width="428" alt="ullyw" src="https://user-images.githubusercontent.com/8294589/37553632-f31e78f6-2a06-11e8-8f58-1c69e156a910.png">

**Comment by mbostock** [comment]
Per the README for [*transform*.rescaleX](https://github.com/d3/d3-zoom/blob/master/README.md#transform_rescaleX):

> Returns a copy of the continuous scale x whose domain is transformed. … The scale x must use d3.interpolateNumber; do not use continuous.rangeRound as this reduces the accuracy of continuous.invert and can lead to an inaccurate rescaled domain.

So no, you can’t use *transform*.rescaleX with a band scale. However, per d3/d3#2442, you can use the zoom behavior to modify a band scale’s range (rather than a continuous scale’s domain, as is more common). Here’s a demo:

https://beta.observablehq.com/@mbostock/d3-zoomable-bar-chart

**Comment by Akshita-Negi** [comment]
You could use clip path where it can be defined as

svg.append("defs").append("clipPath")
    .attr("id", "clip")
  .append("rect")
    .attr("width", width) // width = width of graph area
    .attr("height", height); // height = height of graph area


Check out : https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172
