### ISSUE TITLE
Mouse wheel zoom has very large steps on Firefox (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ohenrik** [d3/d3-zoom#140]
Firefox on Ubuntu (16.04) has extremely large steps when zooming using the mouse wheel, something close to 3x as large as on chrome. Its close not unusable.

I tried reducing the "mousewheel.default.delta_multiplier_y" config variable in Firefox. By setting this down from 100 to 15 i get a scroll speed that is closer to Chrome. However the all scrolling on other pages are slow, pluss i cannot expect users of my website to adjust their scroll settings for Firefox :p

Is there something in D3-zoom i can do to improve this? Is any one else having this issue?

**Comment by Herst** [comment]
Known browser issue: https://stackoverflow.com/q/5527601/2261442 
In the answer to this SO question you will see possible solutions which you can then use you overwrite the default [wheelDelta function](https://github.com/d3/d3-zoom#zoom_wheelDelta).

**Comment by bhousel** [comment]
We implemented a workaround for this in iD:

https://github.com/openstreetmap/iD/blob/f61c482188b1b747fdf528ac2992f6ed9e8a2b6a/modules/renderer/map.js#L376-L396

**Comment by mbostock** [comment]
Closing as this is well-covered by #157 and the existing *zoom*.wheelDelta function.
