### ISSUE TITLE
Can't get d3.zoom working for touch events

### ISSUE THREAD

**Issue by dmosberger** [d3/d3-zoom#141]
I suspect I'm doing something wrong, but after searching far and wide, I don't see the problem.

Background: I'm trying to use d3.zoom (v5.4.0) to pan and zoom a screen area (as in an oscilloscope screen). It's working perfectly fine with the mouse: dragging moves the screen as expected and wheel-action zooms in/out. Beautiful! However, nothing happens on an Android phone (or the Chrome developer's console mobile emulator) when trying to pan with a touch move or zooming with a pinch gesture.

I use a rectangle for receiving the events:

    this.chart.zoomRect = this.chart.el.append('rect')
      .attr('stroke', 'none')
      .attr('fill', '#ff000020')
      .attr('pointer-events', 'all');
and then add the zoom behavior like this:

    this.chart.zoomRect
      .call(d3.zoom()
	    .filter(() => { console.log('event ' + d3.event.type, d3.event); return true})
	    .touchable((a,b,c) => {console.log('touchable', a,b,c); return true})
	    .on('zoom', () => {
	      console.log('event.transform', d3.event.transform);
	      const k = d3.event.transform.k;
	      const x = d3.event.transform.x;
	      this.channelsGroup.attr('transform', (`translate(${x} 0)` + `scale(${k} 1)`));
	    }))
The filter() call, never logs any 'touchmove' events. It does get a 'touchstart' event both on pan and pinch gestures, but nothing during touchmove or pinch-move. On the other hand, the touchable() function does seem to get called during the move events.

I tried adding attribute 'touch-action: none' to the zoomRect, thinking that maybe the browser is trying to handle the touchmove events, but that made no difference.

**Comment by dmosberger** [comment]
Turns out the main problem was that I was getting unexpected ngAfterViewChecked() calls (I'm doing this in Angular) which in turned lead to spurious calls to my resize handler which would then reset the zoom behavior.  Oops.  Now that I fixed this, panning is working great.

Still no luck with pinching for zooming though.

**Comment by dmosberger** [comment]
Oh, just to be clear: now when using the pinch gesture (Shift + drag in the Chrome web developer tools for mobile), I do get zoom events, but d3.event.transform.k is always 1.  Only x and y change.  For example:

```
screen.service.ts:207 event.transform Transform {k: 1, x: -88, y: -170} 5 12.9
screen.service.ts:207 event.transform Transform {k: 1, x: -88, y: -170} 5 12.9
screen.service.ts:207 event.transform Transform {k: 1, x: -88, y: -167} 5 12.9
screen.service.ts:207 event.transform Transform {k: 1, x: -88, y: -166} 5 12.9
screen.service.ts:207 event.transform Transform {k: 1, x: -88, y: -165} 5 12.9
```

**Comment by dmosberger** [comment]
Sorry about the monologue.  Turns out pinch zoom gesture does work on an actual phone, just not in the Chrome web-developers console.

**Comment by Maarondesigns** [comment]
I can't seem to get d3 zoom to work on mobile. When do pinch gesture it usually zooms the whole page, and when I double tap (and sometimes pinch gesture when trying to zoom out) it changes things like stroke-width, but doesn't zoom which is using transform: scale... It sort of works on a touch screen laptop but is very glitchy. Code snippet:

```
  svg = d3
    .select("body")
    .append("svg")
    .attr("id", "world")
    .attr("width", width)
    .attr("height", height)
    .call(d3.behavior.zoom().on("zoom", zoom));

  function zoom() {
    d3.selectAll("#world").attr("transform", "scale(" + d3.event.scale + ")");

    d3.selectAll(".graticule").attr("stroke-width", 0.5 / d3.event.scale);
    d3.selectAll(".pin").attr("stroke-width", 2 / d3.event.scale);
    d3.selectAll(".travelPath").attr("stroke-width", 2 / d3.event.scale);
    d3.selectAll(".land").attr("stroke-width", 1 / d3.event.scale);
    d3.selectAll(".border").attr("stroke-width", 1 / d3.event.scale);
  }
```

**Comment by PiN73** [comment]
If someone faced with shaking, slow pan (dragging) speed and inability to go back after zooming / moving outside of svg:

Try to wrap the svg with div and attach event to the div  instead of svg:
`d3.select(svgContainer).call(d3.zoom().on("zoom", zoomed));`

(In `zoomed` function, apply transform to svg just as before)

**Comment by mbostock** [comment]
Closing to inactivity. Possibly related to #162.
