### ISSUE TITLE
Limit zooming on minimum value of axes

### ISSUE THREAD

**Issue by mmjmanders** [d3/d3-zoom#145]
I'm creating a graph with circles on it, and when clicking a circle the graph zooms to that specific circle centering it. I'm using the `scaleExtent` and `translateExtent` to get this done. However I would like to see the zooming be limited to the minimum value of the axes.
In [this example](https://embed.plnkr.co/N9dlspSihEY3EdvHaOM3/), when clicking on the blue circle the graph zooms in but as you can see the x-axis in this case now has a minimum value displayed of `-5`. The graph should be limited to zero in this case instead of centering the circle.

**Comment by mbostock** [comment]
You can do this, but you’ll need to compute the appropriate transform yourself. We don’t currently enforce constraints on programmatic zooming (so that you have more flexibility).
