### ISSUE TITLE
Mouseup event did not trigger

### ISSUE THREAD

**Issue by zebrallel** [d3/d3-zoom#148]
![2018-07-18 12 21 08](https://user-images.githubusercontent.com/7269427/42859192-13ddad80-8a85-11e8-938a-242d110cc43e.png)

platform: macos 10.13.2  chrome  67.0.3396.99 

My code like this, and in the latest d3 version , 5.5.0, the mouseup event did not trigger. However, I try the version 3.5.0, everything is ok. what's wrong with that?

**Comment by wulucxy** [comment]
@zebrallel I also have this problem, what's reason here?
