### ISSUE TITLE
The default filter should return false if event.ctrlKey.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-zoom#181]
Ref. https://github.com/d3/d3-drag/issues/62

**Comment by MwumLi** [comment]
@mbostock Although  this commit [Fix #181 - ignore control-click.](https://github.com/d3/d3-zoom/commtit/295cb421b1cd1720c5b37722b371211449505402#diff-a51aced82ec54906e9a232d8de465783) solve the curren issue, but it prevents the double-value pinch zoom operation under mac.  

Now, if you want to use the two-finger pinch zoom in the v5 version, you must reset the filter:  
```
zoom.filter(() => !d3.event.button);
```
Look demo:  [Mac 下双指捏合缩放 d3 v5](https://codepen.io/mwumli/pen/JjPMpYL?editors=0010)
