### ISSUE TITLE
iPad zoom issue

### ISSUE THREAD

**Issue by enheit** [d3/d3-zoom#187]
**Current behavior:**
iPad triggers `zoom` event on page scroll.

**Expected behavior:**
Do not trigger `zoom` event while scrolling the page

**Details:**
iOS: 12.4
Browsers: Chrome (74.0.3729.155) & Safari

**Comment by mbostock** [comment]
Are you using d3-zoom 1.8.3?

I’ll also require further explanation because I don’t understand the description. The past release did not properly suppress scrolling when zooming on iOS, but I’ve never heard of zooming being triggered by scrolling.

**Comment by enheit** [comment]
I found a source of issue and it is comes from `onresize` event. 

This issue can be closed.
