### ISSUE TITLE
Pinch zoom in and out not working in mobile chrome

### ISSUE THREAD

**Issue by shofman10** [d3/d3-zoom#194]
When I try to rely on the zoomed event for pinch zooming on mobile devices, it doesn't work well or at all. On my production site it just zooms in to the max scale extent regardless of if I am trying to pinch zoom in or out. 

This is my codepen: https://codepen.io/shofman10/pen/BXxKxJ

Is there different logic I need to add for pinch zooming transformation on mobile devices?

**Comment by Fil** [comment]
Adding a wrapper to apply the zoom transform seems to fix it?
https://codepen.io/recifs/pen/NWGmjRd
