### ISSUE TITLE
Pinch to zoom not working on mac due to ignoring all non-button events when ctrl is active

### ISSUE THREAD

**Issue by tsiki** [d3/d3-zoom#204]
Hello,

It seems https://github.com/d3/d3-zoom/commit/295cb421b1cd1720c5b37722b371211449505402 changed the zooming behavior to filter out any events where control is pressed, but at least in Chrome mac pinch behavior translates to an event where ctrl is true, meaning this change disables mac pinch to zoom by default.

Related SO question: https://stackoverflow.com/questions/59972769/d3-pinch-to-zoom-doesnt-work-in-v5-but-works-in-v4

**Comment by Fil** [comment]
Confirmed. I have restored pinch-to-zoom in [this notebook](https://observablehq.com/d/dc7ed11b703dfcb8) but… it's very very slow, painful to interact with. Zooming with a scroll gesture is much faster.

**Comment by cschweikert** [comment]
I had the same issue. This seemes to be introduces with a fix for preventing dragging with ctrl key. See also d3/d3-drag/issues/62
Since this zooming works as a ctrl+wheel event setting a custom filter like this might help:
```
d3.zoom().filter(function() {
  return (!d3.event.ctrlKey || d3.event.type === 'wheel') && !d3.event.button;
})
```
This will reanable the old zoom behavior and should not interfere with fix d3/d3-drag/issues/62.

**Comment by Fil** [comment]
More documentation here https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e

**Comment by Fil** [comment]
Probably linked to #194

**Comment by Fil** [comment]
I've updated the [test notebook](https://observablehq.com/d/dc7ed11b703dfcb8) with a modified wheelDelta: when the wheel event is received with ctrlKey, we multiply the value by 5. Now it's more on par with the scroll gesture.
