### ISSUE TITLE
dbltap doesn't work on iPad

### ISSUE THREAD

**Issue by Fil** [d3/d3-zoom#206]
Testing d3-zoom (e.g. https://observablehq.com/@d3/zoom-canvas-rescaled or any other) on an iPad, a dbltap doesn't trigger x2 zooming—but a triple tap does. With the pencil it's never triggered, no matter how many "taps".

(On the iPhone dbltap works. )

I'm investigating but it would be nice if someone could confirm or infirm this observation.

**Comment by Fil** [comment]
- I see the same problem with FF, Chrome, and Safari
- the issue of dbltap being inhibited is present with d3-zoom@1.3.1 but not @1.3.0 ([diff](https://github.com/d3/d3-zoom/compare/v1.3.0...v1.3.1))
- adding `.style("touch-action", null); ` makes dbltap operate again
- no versions seems to work with pencil dbltap
- David B. remarks "No issue on BrowserStack's iPad"

**Comment by mbostock** [comment]
I don’t remember what the point of touch-action: none was…

**Comment by Fil** [comment]
It looks like the iPad really wants to deduplicate touchstart: on https://observablehq.com/d/a6c2cfc4e1fad9ea as soon as a touchstart listener is registered, a double-tap creates only one event of each kind (touchstart, mousedown, mousemove, mouseup, click and so on).

A solution might be to switch to Pointer Events (https://observablehq.com/@fil/pointer-events), where this doesn't happen. But it looks to me like an iOS (iPad 13.4.1) bug (?).

**Comment by Fil** [comment]
Re: pencil dbl-tap, the issue is that a touchmove event is received, in which we reset g.taps to 0.

**Comment by Fil** [comment]
Another comment on touch-action… https://github.com/d3/d3-zoom/pull/188#pullrequestreview-280081671

**Comment by Fil** [comment]
After some digging it appears that `touch-action: none` was [added at about the same time](https://github.com/d3/d3-drag/commit/3ca15e46bf97b9eb2218871fba9d10722e38468b) as [this conversation happened](https://github.com/d3/d3-drag/issues/35#issuecomment-314803769). In that case it might be related with enabling something (?) on Surface tablets.
