### ISSUE TITLE
Remove touch-action:none?

### ISSUE THREAD

**Issue by Fil** [d3/d3-zoom#217]
This appears to create various problems:
* with dbltap on the iPad: https://github.com/d3/d3-zoom/issues/206#issuecomment-632895883
* with natural scroll https://github.com/d3/d3-zoom/pull/188#pullrequestreview-280081671

Why it was useful is not documented:  https://github.com/d3/d3-zoom/issues/206#issuecomment-657566655 ; it appears that `touch-action: none` was [added at about the same time](https://github.com/d3/d3-drag/commit/3ca15e46bf97b9eb2218871fba9d10722e38468b) as [this conversation happened](https://github.com/d3/d3-drag/issues/35#issuecomment-314803769). In that case it might be related with enabling something (?) on Surface tablets.

I think I want to remove it from the two branch, and see if we can fix the situation that called for it, if someone finds what it was.

**Comment by Fil** [comment]
Here's another comment about touch-action:none
https://github.com/d3/d3/pull/2403

**Comment by mbostock** [comment]
I don’t recall the context around this change, sorry.
