### ISSUE TITLE
svg.call(d3.zoom().on('zoom',function(){})) warning : Argument of type 'ZoomBehavior<Element, unknown>' is not assignable to parameter of type '(selection: Selection<BaseType, unknown, HTMLElement, any>, ...args: any[]) => void'.

### ISSUE THREAD

**Issue by uniquker** [d3/d3-zoom#246]
typescript verison 4.3.5
d3 version 7.1.0
**code:**
`svg.call(d3.zoom().on('zoom',function(){}))`
**typescript warning:**
Argument of type 'ZoomBehavior<Element, unknown>' is not assignable to parameter of type '(selection: Selection<BaseType, unknown, HTMLElement, any>, ...args: any[]) => void'.
  Types of parameters 'selection' and 'selection' are incompatible.
    Type 'Selection<BaseType, unknown, HTMLElement, any>' is not assignable to type 'Selection<Element, unknown, any, any>'.
      Types of property 'select' are incompatible.
        Type '{ <DescElement extends BaseType>(selector: string): Selection<DescElement, unknown, HTMLElement, any>; <DescElement extends BaseType>(selector: null): Selection<null, undefined, HTMLElement, any>; <DescElement extends BaseType>(selector: ValueFn<...>): Selection<...>; }' is not assignable to type '{ <DescElement extends BaseType>(selector: string): Selection<DescElement, unknown, any, any>; <DescElement extends BaseType>(selector: null): Selection<null, undefined, any, any>; <DescElement extends BaseType>(selector: ValueFn<...>): Selection<...>; }'.
          Types of parameters 'selector' and 'selector' are incompatible.
            Types of parameters 'groups' and 'groups' are incompatible.
              Type 'BaseType[] | ArrayLike<BaseType>' is not assignable to type 'Element[] | ArrayLike<Element>'.
                Type 'BaseType[]' is not assignable to type 'Element[] | ArrayLike<Element>'.
                  Type 'BaseType[]' is not assignable to type 'Element[]'.
                    Type 'BaseType' is not assignable to type 'Element'.ts(2345)

**Comment by Fil** [comment]
What is svg? It should be a d3 selection.

**Comment by uniquker** [comment]
`const svg = d3.select('svg')`
use this code resolve it。
`const svg = d3.select('svg')
function zoomed (event: any) {
  console.log(event)
}
const zoom = zoom().on('zoom', zoomed) as any
svg.call(zoom)`

> What is svg? It should be a d3 selection.

**Comment by uniquker** [comment]
> What is svg? It should be a d3 selection.
`const svg = d3.select('svg')`

**use this code resolve it.**
`const svg = d3.select('svg')
function zoomed (event: any) {
  console.log(event)
}
const zoom = zoom().on('zoom', zoomed) as any
svg.call(zoom)`

**Comment by Robin-Hoodie** [comment]
> > What is svg? It should be a d3 selection.
> > `const svg = d3.select('svg')`
> 
> **use this code resolve it.** const svg = d3.select('svg') function zoomed (event: any) { console.log(event) } const zoom = zoom().on('zoom', zoomed) as any svg.call(zoom)

While it solved the problem, this is not a good idea, using `as any` is essentially the same as turning off TypeScript
