### ISSUE TITLE
Ignore wheel events outside the scale extent.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-zoom#26]
Related d3/d3#2549 d3/d3#2550.

**Comment by mbostock** [comment]
Hmm. This is actually really annoying in practice, since you can’t easily zoom out all the way without also scrolling down:

http://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f

**Comment by mbostock** [comment]
I think what we need to do is consume all wheel events during an active wheel gesture, BUT, if a new wheel gesture starts and you’ve already zoomed out, then we ignore it and let the page scroll down. That way you can zoom out all the way without scrolling down, but if you try to zoom out again, it will then scroll down.

It’d be nice if we ignored wheel events immediately following scroll events, so that you could likewise scroll down without getting sucked into a zoomable element when the mouse enters. But that could lead to other problems, so seems best to ignore that for now.

**Comment by brewmook** [comment]
It would be nice if this behaviour could be switched off (or configure the timeout). I personally find the switching zoom/scroll behaviour a bit annoying even with the timeout.

**Comment by mbostock** [comment]
It’s very easy to add an additional wheel listener that always calls *event*.preventDefault if that is your desired behavior.

**Comment by brewmook** [comment]
Ah, perfect, thanks. :)

**Comment by manake** [comment]
I have this issue in v7.7.0. I zoom in/out all the way and then the mouse wheel starts scrolling `body`.

`d3.event.preventDefault();` and `event.preventDefault();` are not defined in v7.7.0 like described here:
```
selection
    .call(zoom)
    .on("wheel", function() { d3.event.preventDefault(); });
```

Does anyone know what's the current code to disable `body` scrolling while the mouse cursor is over the zoom `rect`?
