### ISSUE TITLE
Referencing width on SVGElement when expected type is actually SVGSVGElement

### ISSUE THREAD

**Issue by BobGneu** [d3/d3-zoom#272]
Good day!

It looks like in `zoom.js` the type check at the head of the function is for an `SVGElement`, but it ought to be the `SVGSVGElement`. 

https://github.com/d3/d3-zoom/blob/main/src/zoom.js#L17-L28

Per the definition on the MDN this results in an opportunity for misuse to result in an element being passed in that is not the outermost SVG element. 

https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement
https://developer.mozilla.org/en-US/docs/Web/API/SVGElement

Also noticed that the repo has not had its open PRs merged in in some time. 
If the there is a maintainer around and interest I can get a PR in for review later in the week. Looks like it should be a really quick changeset.

**Comment by Fil** [comment]
It seems that the code is correctly answering this on line 20 by switching to the ownerSVG, if any:
`e = e.ownerSVGElement || e;`
