### ISSUE TITLE
select(...).transition is not a function

### ISSUE THREAD

**Issue by andzuck** [d3/d3-zoom#275]
See .mov attached:
https://github.com/d3/d3-zoom/assets/3750712/3fb69250-319b-401b-8b78-c59ec17a6650

It seems like the return value of select from d3-selection does not always allow the .transition function to be called safely.

**Comment by mbostock** [comment]
This usually occurs because you have multiple copies of d3-selection (and perhaps d3-transition) installed with different versions, resulting in d3-transition mutating the wrong copy of d3-selection. You should fix this by running `npm update` or equivalent to get consistent installed versions.
