### ISSUE TITLE
zoomTransform not retrieving value set via zoom.transform

### ISSUE THREAD

**Issue by curran** [d3/d3-zoom#34]
From the documentation, it seems that `zoom.transform` should be used to set the transform value on a selection, like this:

```js
var transform = d3.zoomIdentity
  .scale(2)
  .translate(3, 4);

var zoom = d3.zoom();

var svg = d3.select("body").append("svg");

svg.call(zoom.transform, transform);
```

Also from the documentation, it seems that `zoomTransform` should be used to retrieve the value set via `zoom.transform`, like this:

```js
var retrievedTransform = d3.zoomTransform(svg);
```

However, the retrieved transform ends up as the identity transform, rather than the transform previously set.

```js
// Prints "transform = translate(6,8) scale(2)", as expected.
console.log("transform = " + transform);

// Prints "retrievedTransform = translate(0,0) scale(1)".
// This is not expected, it should be the "translate(6,8) scale(2)".
console.log("retrievedTransform = " + retrievedTransform);
```

Here's a [block that reproduces the behavior](http://bl.ocks.org/curran/e29da537fa106f79a4e9894fff4b1606).

Am I misunderstanding the API or might this be a bug?

**Comment by mbostock** [comment]
It’s d3.zoomTransform(*node*), not d3.zoomTransform(*selection*).

http://bl.ocks.org/mbostock/7d17ae828ee83f4302a920ee0c6a9f3d

**Comment by curran** [comment]
Ahh got it. Thank you.
