### ISSUE TITLE
Not Compatible with Brushing

### ISSUE THREAD

**Issue by jasonbodily** [d3/d3-zoom#40]
Creating a brush and zoom chart like this one http://bl.ocks.org/nnattawat/9689303 in version 4 becomes extremely difficult. An infinite loop occurs:

- A zoom event is only able to move the brush using "brush.move". This triggers a brush event.
- The brush event must update the zoom scale and translate which it cannot do except by calling "zoom.transform". 
- This triggers a zoom event...

The zoom could be calculated and set to the node manually but the documentation says this is bad practice. Is there be a way to update the zoom without triggering an event? Previously in V3 you could reset the scale, I believe.

**Comment by mbostock** [comment]
Use d3.event.sourceEvent to break the infinite loop.

```js
function brushed() {
  if (d3.event.sourceEvent && d3.event.sourceEvent.type === "zoom") return; // ignore brush-by-zoom
  …
}

function zoomed() {
  if (d3.event.sourceEvent && d3.event.sourceEvent.type === "brush") return; // ignore zoom-by-brush
  …
}
```

http://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

**Comment by jasonbodily** [comment]
A million thanks for recreating that example! I'd been looking for it!
