### ISSUE TITLE
Zoom allow horizontal scrolling, or wheel on drag

### ISSUE THREAD

**Issue by jasonbodily** [d3/d3-zoom#46]
Zooming leverages the vertical aspect of the mouse wheel as shown in http://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172, but can zoom also allow for horizontal movement on a zoom that doesn't use it's Y scale (timelines, eg.)? Instead of having to drag horizontally, it would be much quicker to scroll left and right (iMovie editor section, e.g.). If scrolling is not an option, at least extending the drag so that it can be given the momentum effect the 'wheel' provides would provide for a better experience in many of the cases I've come across.

The zoom event has a deltaX on it, which I am trying to use in place of the zoom effect when the scrolling is primarily horizontal (abs(deltaX) >= abs(deltaY)). For an example of how this works, simply scroll your browser on a page that isn't overflowing horizontally. The page vertically scrolls up and down without any horizontal shift until ample horizontal action is detected and the page budges left and right.

Below is is the pattern I've been trying to follow, but I run into a lot of issues (trying to set the zoom retriggers the zoom event, setting the offset on the event transform doesn't persist, locking the scaling seems problematic, nested elements don't respond to the horizontal zoom and instead the 'back' on browser history is triggered). Has any consideration been given to this sort of fx.

``` javascript
var zoom_direction,
      zoom = d3.zoom()
            .extent([[0, 0], [width, container_height]])
            .translateExtent([[0, 0], [width, container_height]])
            .on('zoom', zoomed)
            .on('start', stashZoomTransform)
            .on('end', () => zoom_direction = undefined);

function zoomed() {
            let t = d3.event.transform;
            if (!zoom_direction) {
                  zoom_direction; // set to 'horizontal' if deltaX is more significant then deltaY
            }
            // if zoom_direction is horizontal
                // lock or reset scaling to the stashed zoomTransform 
                // Set transform offset according to deltaX 
                // Reapply new transform to node
}
```

I tried all day to come up with a solution, but haven't managed it. Any insights would be appreciated.

**Comment by mbostock** [comment]
I would probably override the `wheel.zoom` event listener on the element you applied the zoom behavior to, so as to substitute your interpretation of the input event in place of the normal zoom behavior’s interpretation. For example:

```js
var zoom = d3.zoom()…;

selection
    .call(zoom)
    .on("wheel.zoom", wheeled);
```

A capturing wheel event listener that calls *event*.stopImmediatePropagation would also work, but it’s acceptable to replace or unbind event listeners registered by the zoom behavior to customize the behavior.

(If you want to trigger the zoom behavior within a zoom event, typically you use d3.event.sourceEvent to break the infinite loop.)

In the long run, it might be reasonable for the zoom behavior to be more customizable, perhaps supporting multiple modes of interpretation for wheel events. ([ArcGIS](https://www.arcgis.com/home/webmap/viewer.html?webmap=027d4f1968dd4162b0f8b63a72659f2c&zoom=true), for instance, uses wheel events to pan. You can zoom-in by shift-dragging a region or double-clicking, but as far as I can tell there’s no way to zoom out without using an on-screen button, which is somewhat unfortunate. Also see [Zoom to Brush](https://bl.ocks.org/mbostock/f48fcdb929a620ed97877e4678ab15e6) for an example of zooming to a rectangular region.) Supporting multiple modes of interpretation will probably make the code messy, though, so it might be nice to figure out a better way of encapsulating the logic. Maybe?

**Comment by jasonbodily** [comment]
A default might be nice. Could it be implemented similar to the dot walking on events that is elsewhere? For example, 'wheel.zoom.horizontal' vs 'wheel.zoom.vertical'? 

For the interim I've got a start on what it looks like:

```
// Build Dimensions and SVG object 

 var zoom = d3.zoom()
    .extent([[0, 0], [width, container_height]])
    .translateExtent([[0, 0], [width, container_height]])
    .on('zoom', zoomed);

var g = svg.append('g')
    .call(zoom)
    .on("wheel.zoom", wheeled);

function wheeled() {
    let event = d3.event,
        dx = Math.abs(event.deltaX),
        dy = Math.abs(event.deltaY);
    if (dx > dy) {
        zoom.translateBy(canvas, event.deltaX);
        tUpdate(d3.zoomTransform(canvas.node()));
    } else if (dx < dy) {
        let new_scale = 1; // How do you make a new scale here?
        zoom.scaleBy(canvas, new_scale);
        tUpdate(d3.zoomTransform(canvas.node()));
    }
    event.preventDefault && event.preventDefault();
}

function zoomed() {
    if (d3.event.sourceEvent && d3.event.sourceEvent.type === 'wheel') { return; }
    tUpdate(d3.event.transform());
} 

function tUpdate(transform) {
    //Update view
}
```

It brings up three questions: 

1. Is how do I calculate the new scale on a vertical movement from the event object. I've looked at the source code and can see a formula there, but is there a more native way to derive the new scale? 
2. is 'Is d3.zoomTransform(canvas.node()) the best way to access the transform in these situations?' 
3. Programmatically triggering zooms calls the 'start' and 'end' events on each loop. Is there a way to detect the beginning of a swipe so that full swipes can be assigned to vertical or horizontal movement? (not as important)

**Comment by mbostock** [comment]
1. Not sure what else I can say other than what you have already looked at in the source code. If there were a simpler way to do it I would have done it. 😜

2. `d3.zoomTransform(this)`. You could also use `this.__zoom` but it is a private API.

3. Again, see the source. I used a timer to group a sequence of wheel events into a gesture.

**Comment by jasonbodily** [comment]
Thanks!

**Comment by jasonbodily** [comment]
For those interested, my implementation looks like this:

```
function wheeled() {
            var  event = d3.event,
                dx = Math.abs(event.deltaX),
                dy = Math.abs(event.deltaY),
                t = d3.zoomTransform(this);
            if (dx > dy) {
                zoom.translateBy(canvas, -event.deltaX * 2 / t.k);
                updateView(d3.zoomTransform(this));
            } else if (dx < dy) {
                // Rescale
                let k = t.k * Math.pow(2, -event.deltaY * (event.deltaMode ? 120 : 1) / 500);
                zoom.scaleTo(canvas, k);
                // Retranslate
                let t2 = d3.zoomTransform(this), // reaccess the transform so that the zoom's extents apply
                    p = d3.mouse(this), // We're going to shift by a point
                    w = scales.x.range()[1], // My scales reference
                    dw = (w / t2.k) - (w / t.k), // The change in width
                    x = dw / 2 - dw*(p[0] / w); // Account for shift by scale
                zoom.translateBy(canvas, -x, 0);
                updateView(d3.zoomTransform(this));
            }
            return event.preventDefault && event.preventDefault();
        }
```

**Comment by mbostock** [comment]
Closing as I have no immediate plans to add this to d3-zoom. Thanks for sharing your implementation!

**Comment by watert** [comment]
> For those interested, my implementation looks like this:
> 
> ```
> function wheeled() {
>     var event = d3.event,
>         dx = Math.abs(event.deltaX),
>         dy = Math.abs(event.deltaY),
>         t = d3.zoomTransform(this);
>     if (dx > dy) {
>         zoom.translateBy(canvas, -event.deltaX * 2 / t.k);
>         updateView(d3.zoomTransform(this));
>     } else if (dx < dy) {
>         // Rescale
>         let k = t.k * Math.pow(2, -event.deltaY * (event.deltaMode ? 120 : 1) / 500);
>         zoom.scaleTo(canvas, k);
>         // Retranslate
>         let t2 = d3.zoomTransform(this), // reaccess the transform so that the zoom's extents apply
>             p = d3.mouse(this), // We're going to shift by a point
>             w = scales.x.range()[1], // My scales reference
>             dw = (w / t2.k) - (w / t.k), // The change in width
>             x = dw / 2 - dw*(p[0] / w); // Account for shift by scale
>         zoom.translateBy(canvas, -x, 0);
>         updateView(d3.zoomTransform(this));
>     }
>     return event.preventDefault && event.preventDefault();
> }
> ```

also my implement is below
* removed updateView because seems like it can done by `on('zoom', func)`
* added y position translate
* get canvas by `d3.select(this)`

```
function wheeled() {
  const canvas = d3.select(this);
  var event = d3.event,
      dx = Math.abs(event.deltaX),
      dy = Math.abs(event.deltaY),
      t = d3.zoomTransform(this);
  if (dx > dy) {
    zoom.translateBy(canvas, -event.deltaX * 2 / t.k, 0);
  } else if (dx < dy) {
    // Rescale
      let k = t.k * Math.pow(2, -event.deltaY * (event.deltaMode ? 120 : 1) / 500);
      zoom.scaleTo(canvas, k);
      // Retranslate
      let t2 = d3.zoomTransform(this), // reaccess the transform so that the zoom's extents apply
          p = d3.mouse(this), // We're going to shift by a point
          w = zoom.xScale.range()[1], // My scales reference
          dw = (w / t2.k) - (w / t.k), // The change in width
          h = zoom.yScale.range()[1], // My scales reference
          dh = (h / t2.k) - (h / t.k),
          x = dw / 2 - dw*(p[0] / w),
          y = dh / 2 - dh * (p[1] / h)// Account for shift by scale
        ; 
      zoom.translateBy(canvas, -x, -y);
  }
  return event.preventDefault && event.preventDefault();
}
```
