### ISSUE TITLE
Optional round to power-of-two zooming?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-zoom#5]
It seems weird to round to power-of-two on dblclick, but not do it on wheel or touch. (Google Maps doesn’t round to power-of-two in WebGL mode.)

**Comment by ondras** [comment]
The "wheel" event is remarkably un-configurable, including the hardcoded `500` constant. I would like to have some options here.

1) would a PR including support for dynamic configuration of this `500` value be wanted/accepted?

2) alternatively, what about a user-specified callback that converts a normalized wheel delta value to the final `k` value?

**Comment by ondras** [comment]
@mbostock what is your opinion re. my previous comment? Would you accept a PR as described?

**Comment by mbostock** [comment]
Your comment is unrelated to this issue, which is about whether the dblclick event should round to the nearest power-of-two zoom level, or alternatively whether the wheel and touch gestures should round to the nearest power-of-two zoom level after the gesture ends.

If you want an immediate solution, you can remove or replace the *wheel* event listener registered by the zoom behavior:

```js
selection
    .call(zoom) // Register the zoom behavior as normal.
    .on("wheel.zom", wheeled); // Replace the wheel listener with your own.
```

In your `wheeled` function, you can then programmatically drive the zoom behavior however you like using *zoom*.transform.

I think it’d be reasonable to have a *zoom*.wheelDelta function whose default implementation is:

```js
function wheelDelta() {
  return -d3.event.deltaY * (d3.event.deltaMode ? 120 : 1) / 500);
}
```

This function could then be configured (optionally [as a constant](https://github.com/d3/d3-zoom/blob/master/src/constant.js), which is then promoted to a function) to change the behavior.

**Comment by ondras** [comment]
> Your comment is unrelated to this issue, which is about whether the dblclick event should round to the nearest power-of-two zoom level, or alternatively whether the wheel and touch gestures should round to the nearest power-of-two zoom level after the gesture ends.

I am terribly sorry for using a wrong issue. I considered this one as a general question of d3-zoom's configurability (especially regarding the `wheel` event).

> If you want an immediate solution, you can remove or replace the wheel event listener registered by the zoom behavior:

I am aware of this approach. But rather than introducing a custom solution, improving D3's sounds like a better idea to me.

> I think it’d be reasonable to have a zoom.wheelDelta function whose default implementation is:

Cool, I will try to hack something together and send a PR.

Sorry again for posting in a wrong place.

**Comment by mbostock** [comment]
Power-of-two rounding on dblclick was removed in 31d895f69b24429c0f6e38e1042235c873be9a69.

**Comment by mbostock** [comment]
If we allow *zoom*.scaleBy to take a reference point #178, rather than using only the viewport centroid, then this will be fairly easy to do programmatically, so I don’t think we need a separate issue for this special case.
