### ISSUE TITLE
zoom resetting invoking panning not at current zoom level

### ISSUE THREAD

**Issue by syarul** [d3/d3-zoom#53]
``zoomIdentity`` does not reset pan, only zoom values. Panning will use previous zoom level.

```javascript
chart.transition()
    .duration(750)
    .call(zoom.transform, d3.zoomIdentity);
```

**Comment by mbostock** [comment]
Works for me?

http://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f/541b7d087ff21635423a4e7f92c5542e0cca8295

If you want to report an issue, please link to a live example on bl.ocks.org that reproduces the issue. A code snippet out of context is rarely sufficient to demonstrate a bug. Thank you!

**Comment by syarul** [comment]
Alright thanks, will look into it.

**Comment by marcusklaas** [comment]
You've probably long solved this yourself, but for any one running into this later (like me), you may be calling the transform on the wrong element. Specifically, I had to call
```
svg.transition()
    .duration(750)
    .call(zoom.transform, d3.zoomIdentity);
```
where `svg` would be the parent of `chart`.
