### ISSUE TITLE
Handle orphaned gestures.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-zoom#60]
The equivalent of d3/d3-brush#18, but for d3-zoom. If the browser fails to deliver a _mouseup_ (or _touchend_ or _touchcancel_) event, the active gesture can get orphaned, in which case no new gestures can start or end.

**Comment by MarkusMannheim** [comment]
May I get an update on this? This affects all of my scripts that use `d3.zoom()` when accessed via mobiles/touchscreens. When the user pinches to zoom in/zoom out, and then tries to pan by dragging with a single touch, the program behaves as though two fingers are still touching the screen - i.e. it doesn't fire a touchend/touchcancel event, or enough touchend/touchcancel events.

Is there a workaround?
