### ISSUE TITLE
Click event handling breaks easily on Chrome

### ISSUE THREAD

**Issue by McGiogen** [d3/d3-zoom#62]
Hi,
I got a weird behaviour on an horizontal tree with zoom: after some fast and random clicks on my tree, where every click expands or collapses a node, I am no more able to do it and the only thing that works is zoom. Disabling zoom fixes the problem, both commenting the call to d3.zoom and using filter on "mousedown". The problem is that I can't disable d3.zoom and I can't filter on mousedown because I'm using it to pan the tree (only to do it, not to zoom).

[My example](https://plnkr.co/edit/rEOtHK?p=preview) is big and complex but you only have to focus on low number of lines.

How to reproduce
====================
- Open [my example](https://plnkr.co/edit/rEOtHK?p=preview) **on Chrome**
- Click con nodes randomly and faster as you can for some seconds, until they expand/collapse no more
- Note that panning is still working (if the tree is larger than your windows, because of the code)

Find the code
====================
The zoom call is in file `treeUtils.zoom.js`, inside function `addController`, lines 93-116.
The `click` function is in file `script.js`, lines 727-750.

--------------------------

The problem occurs more often on Chrome but it is reproducible also on Firefox (at least).

This is my first and big work with d3 but I think everything should works.

Ps: I've also read [this issue](https://github.com/d3/d3/issues/2887) but I have found nothing useful.

**Comment by mbostock** [comment]
Sorry, but this example is too large for me to investigate. In addition, the user interface introduced by Plunker impedes running the debugger. If you’d like me to investigate this issue, please reduce the example and post it to http://bl.ocks.org (via https://gist.github.com).

It appears you can reproduce the problem just by double-clicking on a node. Your code was too large to investigate, but perhaps you are doing something on click that is interfering with the zoom transition, putting the zoom behavior into a broken state. You’ll probably want to disable the dblclick.zoom listener if you are already doing something on click that would interfere with the zoom event… or perhaps calling *event*.preventDefault on click if you aren’t already; perhaps that prevents a subsequent *dblclick*?

It also wasn’t clear whether your tree is zoomable or just pannable, so using d3-drag might be a simpler solution, too.

**Comment by McGiogen** [comment]
I've really simplified my code and it is on [bl.ocks](https://bl.ocks.org/McGiogen/d9c1532544bc484caaebd81a94f81b4e), this is [plunker link](https://plnkr.co/edit/rEOtHK?p=preview), if someone want it.

I noticed that the problem is reproducible in a really simple way: click a node and rapidly pan the view.
Now double clicking should no more be a problem, it seems that it didn't like `.on('dblclick.zoom', null)` line of code, but I don't need it.

I've also tried event.preventDefault and event.stopPropagation on click but has not solved.

I think that the only thing that could be a problem is the function `navigateAtNode` (in file treeUtils.zoom.js) that moves the view when you click on a node, if necessary... Do you think that its code is wrong?

**Comment by mbostock** [comment]
My guess is that the zoom transition you are creating in navigateAtNode is interrupting or being interrupted by the zoom transition created by the zoom behavior on dblclick, and likewise the zoom transition you create in navigateAtNode would be interrupted by any interaction (panning). But it’s hard to tell whether the problem lies in your application state or in d3-zoom, as this example is still fairly large.

**Comment by McGiogen** [comment]
Ok, following your comment I finally fixed it.

I changed the way used to move the tree programmatically. Instead of
```
zoomControllerElement
    .transition().duration(DURATION)
    .call(zoom.transform, d3.zoomIdentity.translate(-newX, 0));
```
I've used
```
zoomControllerElement.select('g.zoomContainer')
    .transition().duration(DURATION)
    .attr('transform', d3.zoomIdentity.translate(-newX, 0));
```
and I added an event listener to stop the animation if the user starts to pan manually (to the invisible rect used to zoom/pan from everywhere):
```
zoomControllerElement.select('rect.zoomBackground')
    .on('mousedown dragstart click touchstart', function () {
        // This stops pan transition
        zoomControllerElement.select('g.zoomContainer').transition();
    });
```

I've updated both [plunker](https://plnkr.co/edit/rEOtHK?p=preview) and [gist](https://bl.ocks.org/McGiogen/d9c1532544bc484caaebd81a94f81b4e) if someone will needs them.

**Comment by herrvigg** [comment]
hello,
this issue looks very similar to the one i opened recently: https://github.com/d3/d3-zoom/issues/66

If i reassume, panning on an item part of an element having a zoom behavior makes the click events lost.

I don't know if this is supposed to be the case with the new zoom in v4, it's not easy to understand what is meant with the prevent default stuff and so on. But what is sure, this used to work in v3 and does not work anymore in v4.

Is this supposed to work like this now? If yes, how can i correctly capture click events on items part of a zoomable container?

**Comment by dqueffeulouatw** [comment]
The example in Plunker https://plnkr.co/edit/rEOtHK?p=preview doesn't work in Chrome (Version 55.0.2883.87 m (64-bit)) but works in Firefox (50.1.0).
When I click on MAURIZINI, the node is expanded in Firefox but not in Chrome.
So I think there is still a problem with Chrome.
I have similar issue with Chrome combining d3 zoom and click on SVG object.

**Comment by McGiogen** [comment]
I use Chrome 55.0.2883.87 (64-bit) on Linux and it is working

**Comment by dqueffeulouatw** [comment]
Ok, I forgot to mention Chrome on Windows (7/64).

**Comment by dqueffeulouatw** [comment]
Actually, I have a collegue with Chrome also but no click problem so it's a bit weird. I will investigate.

**Comment by dqueffeulouatw** [comment]
Sorry for my previous message, I have restarted Chrome and now the Plunker example is working like in Firefox.

**Comment by m1dst** [comment]
I see a similar issue where FF always seems stable, Chrome stays stable for a while and then stops working.  Restarting the PC fixes the issue in Chrome.  It isn't clear to me if the issue is within Chrome or D3.  What I find when it stops working is ALL click events stop working completely within the D3 container.  I can zoom with the scroll wheel but all click events are ignored and don't hit my breakpoints.  Very weird and difficult to repro.

**Comment by dqueffeulouatw** [comment]
@m1dst yes I have this behavior too. I don't think you need to restart the PC but just Chrome (all processes).
I don't know how to fix it in code.

**Comment by iainbryden** [comment]
I have this problem too: Windows 7/64, Chrome.

I created a forced layout with .on('click') events for every node. Clicks register after 1, 2, or 3 clicks. I tested in Firefox and the events fire on the first click.

**Comment by tomexx** [comment]
@iainbryden Do you have an example somewhere please?

**Comment by thomazrezende** [comment]
@mbostock @McGiogen if you're using pen tablets instead of mouse, this error could be outside D3 code. I was facing a similar issue in my computer and realised that the problem was a partial lost of communication between my pen tablet and chrome when using Mac's application switcher. I have a Wacom CTL-480 Intuos and a driver update solved this issue for me (most of it).

**Comment by codethief** [comment]
I've been experiencing the same issue and suggest we reopen this bug.

Some details:
- The issue seems to only occur on Chrome
- The issue is very difficult to reproduce and only appears every now and then
- The issue prevents any click that occurs on the viewport (i.e. the element to which the zoom behavior was assigned) from being registered. Meanwhile, hover effects etc. work fine.
- Using Chrome's developer tools one can see that it's d3-zoom's `mouseDown` event handler on the viewport that causes this and prevents clicks from getting registered and reaching `onClick` event handlers.

**Comment by B1ll1** [comment]
I agree with @codethief, I'm still having this same issue from time to time.

**Comment by codethief** [comment]
I did some further investigation: According to [this posthttps://stackoverflow.com/questions/49808356/d3-mousedown-event-fires-but-mouseup-event-does-not-fire) on SO or, more precisely, @mbostock's comment [here](https://github.com/d3/d3-zoom/issues/66#issuecomment-255175895), the zoom behavior should fully consume the mouse-down event but, if I understand correctly, clicking should still work in general.

However, it seems that, on *some* occasions on Chrome, the fact that d3-zoom's mouse-down event handler swallows the mouse-down event actually prevents any click event from getting triggered at all.

**Comment by B1ll1** [comment]
"However, it seems that, on *some* occasions on Chrome, the fact that
d3-zoom's mouse-down event handler swallows the mouse-down event actually
prevents any click event from getting triggered at all."

This is exactly the point that I found, some times the click event stops at
the mousedown and it only starts working again after reopening the chrome
browser
