### ISSUE TITLE
PhantomJS does not implement SVGAnimatedLength.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-zoom#63]
@LiamKarlMitchell writes in d3/d3#2991:

Getting an error with SVGSVGElement not having a width property implemented with PhantomJS, (I'll probably lodge an issue with them as well).

I figure it gets the width and height of the parent SVG element.

In Google Chrome the SVG node has a .width property as an instance of SVGAnimatedLength
One thing that comes to mind is that this might be used for the case of SVG inside SVG with animation/translation on them?

```
function defaultExtent() {
  var e = this, w, h;
  if (e instanceof SVGElement) {
    e = e.ownerSVGElement || e;
    w = e.width.baseVal.value;
    h = e.height.baseVal.value;
  } else {
    w = e.clientWidth;
    h = e.clientHeight;
  }
  return [[0, 0], [w, h]];
}
```

I ended up wrapping it in a try catch.
Tried to add properties to the SVGSVGElement object for width and height but it just would not use them.

```
  function defaultExtent() {
    var e = this, w, h;
    if (e instanceof SVGElement) {
      e = e.ownerSVGElement || e;
      try {
        w = e.width.baseVal.value;
        h = e.height.baseVal.value;
      } catch (e) {
        w = this.clientWidth;
        h = this.clientHeight;
      }
    } else {
      w = e.clientWidth;
      h = e.clientHeight;
    }
    return [[0, 0], [w, h]];
  }
```

Maybe not an ideal fix.

**Comment by mbostock** [comment]
D3 is not a compatibility layer. If a platform (such as PhantomJS) does not correctly implement the standard, it’s the responsibility of the platform to fix itsself and not D3 to implement a workaround.

That said, I might be willing to make a small change if it’s not overly burdensome. Perhaps this:

```js
function defaultExtent() {
  var e = this, w, h;
  if (e instanceof SVGElement) {
    e = e.ownerSVGElement || e;
    w = +e.getAttribute("width");
    h = +e.getAttribute("height");
  } else {
    w = e.clientWidth;
    h = e.clientHeight;
  }
  return [[0, 0], [w, h]];
}
```

However, I’m not sure whether this will work if width and height attributes are not specified (and left as their default value), and whether it will work if the width and height attributes are specified with units (if that’s even possible according to the specification).

**Comment by mbostock** [comment]
An interim workaround would be for you to specify a *zoom*.extent explicitly (that uses clientWidth and clientHeight, or whatever) rather than relying on the default implementation for PhantomJS.

**Comment by LiamKarlMitchell** [comment]
Fair enough,

Thanks for your input.

**Comment by evanjmg** [comment]
It's the same issue on Chrome Launcher. The quick fix for now works for me as well.

**Comment by mbostock** [comment]
Closing to inactivity, plus the fact that D3 is not a compatibility layer.
