### ISSUE TITLE
Ability to disable double click event/choose which events are enabled?

### ISSUE THREAD

**Issue by joyt** [d3/d3-zoom#69]
My application already has implemented a separate behavior for the double click event, but now the zoom behavior is overriding it, is there a way to disable this functionality selectively?

**Comment by mbostock** [comment]
Per the [API reference](https://github.com/d3/d3-zoom/blob/master/README.md#api-reference) for [*zoom*.duration](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_duration):

> To disable double-click and double-tap transitions, you can remove the zoom behavior’s dblclick event listener after applying the zoom behavior to the selection:
> 
> ```js
selection
    .call(zoom)
    .on("dblclick.zoom", null);
```

**Comment by joyt** [comment]
Thanks!
