### ISSUE TITLE
zoom.transform - transition + duration doesn't consistently zoom smoothly. 

### ISSUE THREAD

**Issue by KilianCollender** [d3/d3-zoom#71]
When applying a new zoom transform on a svg selection as shown below, the smooth zooming isn't always consistent. 
`svgSelection.transition().duration(1000).call(zoom.transform, transform);`

If I watch the value of `d3.zoomTransform(svgSelection.node())` I can see that sometimes the transform updates over the duration, giving the smooth zoom. However sometimes this action applies the final transform in the first iteration, leading to a jumping effect.

**Comment by mbostock** [comment]
Please link to a live example that exhibits the issue in bl.ocks.org if you would like me to investigate. Otherwise I have no way of reproducing the issue.

http://bl.ocks.org/mbostock/b783fbb2e673561d214e09c7fb5cedee
