### ISSUE TITLE
D3 zoom not working with mousewheel in safari Version 10.0 (Mac)

### ISSUE THREAD

**Issue by vbabenko** [d3/d3-zoom#76]
The issue is reproduced only in Safari (FireFox, Chrome works as expected).
I'm using last version of D3 (4.2.2 and 4.4)
The problem that D3 wheel zoom works only on `g` element and doesn't work over `svg` element. Note `dbClick` zoom works over `svg`.

Steps of reproduce (Safari):
1) Mouse over on red rect and start wheel zoom
>> zoom works
2) Mouse over on svg element near of red rect
>> zoom doesn't work

Note: there is exists some zones in svg (left and top) where zoom works. This illustration described in [stackoverflow](http://stackoverflow.com/questions/40887193/d3-js-zoom-is-not-working-with-mousewheel-in-safari) link. 

Reproduce of issue: https://bl.ocks.org/mbostock/91b75091873d06add0666f35c2e6afb4
JS fiddle for any case: https://jsfiddle.net/vbabenko/5shshq97/7/

Solution to fix:
If you want the SVG to receive the event on all browsers, you must put some content in the SVG to capture the wheel event. Here is a fixed test case: https://bl.ocks.org/mbostock/9e3fed7a5904991e7973a87628d9f84d

comments taken from the ticket https://github.com/d3/d3/issues/3035

**Comment by mbostock** [comment]
Closed per https://github.com/d3/d3/issues/3035#issuecomment-266066432

**Comment by karlcow** [comment]
https://bugs.webkit.org/show_bug.cgi?id=226683
