### ISSUE TITLE
Using .on("wheel", ...) to cancel zoom doesn't work

### ISSUE THREAD

**Issue by joshhobson** [d3/d3-zoom#80]
Using `.on("wheel", function() { d3.event.preventDefault(); });` as per https://github.com/d3/d3-zoom/blob/master/README.md#zoom_scaleExtent doesn't seem to do anything. 

See http://bl.ocks.org/joshhobson/cfc612a0b42531ad6e7fcccc49e07faf (an exact clone of http://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172 with the line above added.)

My fix was to add the following to my zoom function 
`
if (d3.event.sourceEvent && d3.event.sourceEvent.type === "wheel") {
   return;
 }  // disable scrolling
`

**Comment by mbostock** [comment]
Are you trying to cancel scrolling or zooming?

Calling *event*.preventDefault prevents the browser’s default native behavior on wheel, which is typically scrolling, not zooming. It doesn’t disable zooming. If you want to disable zooming on wheel, you can remove the zoom behavior’s wheel listener like so:

```js
selection
    .call(zoom)
    .on("wheel.zoom", null);
``` 

(You’ll still be able to pan by clicking and dragging, and zoom using touch events, however.) If you want complete control over which events initiate zoom, then do not use *selection*.call(*zoom*) and instead use the *zoom* behavior programmatically via [*zoom*.transform](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_transform). Or use [*zoom*.filter](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_filter).

If you want to ignore events in your own listener, then you can do that too, as you said.

So perhaps I don’t understand the issue but I don’t see a problem here.

**Comment by joshhobson** [comment]
Thanks Mike! I couldn't find this in the docs. I am indeed disabling "scroll to zoom" while allowing normal page scrolling so this worked perfectly.
