### ISSUE TITLE
Wrong center when zoom with scaleBy and using svg with viewBox attribute

### ISSUE THREAD

**Issue by AutomationEngineer** [d3/d3-zoom#85]
Issue:
scaleBy function zoom center may be off the actual center if viewBox attribute of svg container is used.

Expected behavior:
scaleBy function zoom center is equal to actual center of svg container regardless of viewBox attribute

The with and height of my svg container depends on the size of browser window, and I use viewBox attribute to scale and center image initially. I also have d3 zoom functionality enabled and it work fine with the mouse, but I have added zoom in and out buttons recently (scaleBy), and see the zoom center is off from the actual svg container center.
https://jsfiddle.net/VictorKulikov/1kq31ex6/
When I remove viewBox attribute buttons works fine and the center of zoom is correct.
https://jsfiddle.net/VictorKulikov/1kq31ex6/1/

**Comment by mbostock** [comment]
The problem is that you are relying on the default [*zoom*.extent](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_extent), which is defined as [[0, 0], [*width*, *height*]]:

> If *extent* is not specified, returns the current extent accessor, which defaults to [[0, 0], [*width*, *height*]] where *width* is the [client width](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) of the element and *height* is its [client height](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight); for SVG elements, the nearest ancestor SVG element’s [width](https://www.w3.org/TR/SVG/struct.html#SVGElementWidthAttribute) and [height](https://www.w3.org/TR/SVG/struct.html#SVGElementHeightAttribute) is used. In this case, the owner SVG element must have defined [width](https://www.w3.org/TR/SVG/struct.html#SVGElementWidthAttribute) and [height](https://www.w3.org/TR/SVG/struct.html#SVGElementHeightAttribute) attributes rather than (for example) relying on CSS properties or the viewBox attribute; SVG provides no programmatic method for retrieving the [initial viewport size](https://www.w3.org/TR/SVG/coords.html#ViewportSpace). Alternatively, consider using [*element*.getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect). (In Firefox, [*element*.clientWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) and [*element*.clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) is zero for SVG elements!)

So, the easiest thing is probably to set the *zoom*.extent explicitly to match your viewbox, like so:

```js
var zoom = d3.zoom()
    .scaleExtent([1/2, 4])
    .extent([[0, 0], [width / 2, height / 2]])
    .on("zoom", zoomed);
```

**Comment by AutomationEngineer** [comment]
Oh, sorry for posting issue which is not an issue. Solution with .extent() works very well for me, thanks!
