### ISSUE TITLE
Panning with mousewheel or right mouse button

### ISSUE THREAD

**Issue by sebamarynissen** [d3/d3-zoom#91]
According to my knowledge, panning is by default "LMB-only":
```javascript
// Ignore right-click, since that should open the context menu.
function defaultFilter() {
  return !event.button;
}
```
I am experiencing an issue where I would like to be able to pan with the mousewheel or as the RMB as well. Unfortunately however, in the zoom function there is no way to change this behavior.
```javascript
export default function() {
  var filter = defaultFilter,
  // [...]
};
```
It would be nice to have the possibility to change the default filter, for example like this
```javascript
export default function(opts) {
  var opts = opts || {};
  var filter = opts.filter || defaultFilter;
};
```
which allows one to do
```javascript
var zoom = d3.zoom(function() {
  // This should allow RMB panning.
  return window.event.button === 2;
});
selection.call(zoom);
```

**Comment by mbostock** [comment]
See [*zoom*.filter](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_filter) to change the filter function.

**Comment by sebamarynissen** [comment]
My apologies, did search for it for over an hour, probably not in a good way. -_-

**Comment by isbdnt** [comment]
```javascript
d3.zoom().filter(function () {
    switch (d3.event.type) {
        case "mousedown": return d3.event.button === 1
        case "wheel": return d3.event.button === 0
        default: return false
    }
})
```
