### ISSUE TITLE
d3.zoomIdentity.translate().scale() vs. d3.zoomIdentity.scale().transform()

### ISSUE THREAD

**Issue by Mavromatika** [d3/d3-zoom#95]
Hi,
When trying to implement a custom transform to zoom in on specific elements (inspired by your "zoom to bounding box" example), I realized that `d3.zoomIdentity.translate().scale()`  and `d3.zoomIdentity.scale().transform()` don't return the same transform. The first one works as expected, but the second doesn't (in that the computed translate to center the element on the screen doesn't work properly). 

Here's an example : 
```
<!DOCTYPE html>
<meta charset="utf-8">
<p>Click on a circle to zoom in on it.</p>
<svg></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
<script>

var w = 500, h = 400;
var svg = d3.select("svg")
            .attr("width",w)
            .attr("height",h)
            .style("border","1px solid black");
    
svg.append("line").attr("x1",w/2).attr("x2",w/2).attr("y1",0).attr("y2",h).attr("stroke","black");
svg.append("line").attr("x1",0).attr("x2",w).attr("y1",h/2).attr("y2",h/2).attr("stroke","black");

var pointsData = d3.range(0,10,1);
    
var scalePoints = d3.scalePoint()
                .domain(pointsData)
                .range([0,w]);
    
var color = d3.scaleSequential(d3.interpolatePiYG);
    
var points = svg.selectAll("circle")
                .data(pointsData)
                .enter()
                .append("circle")
                .attr("cx",function(d){return scalePoints(d);})
                .attr("cy",h/2)
                .attr("r",10)
                .attr("fill",function(d,i){return color(i/pointsData.length);});

var zoomFunc = d3.zoom()
    .scaleExtent([1 / 2, 4])
    .on("zoom", zoomed);
    
svg.call(zoomFunc);
    
function zoomed(){
    points.attr("transform",d3.event.transform);
}
    
points.on("click",function(d){
   var scale = 2;
    // This works as expected
    var transform = d3.zoomIdentity
                    .translate(w/2 - scalePoints(d)*scale , h/2 * (1 - scale))
                    .scale(scale);
    // but that doesn't.
//    var transform = d3.zoomIdentity
//                    .scale(scale)
//                    .translate(w/2 - scalePoints(d)*scale , h/2 * (1 - scale));
    
    svg.transition().duration(300).call(zoomFunc.transform, transform);
});
</script>
```
Is that supposed to be that way ? Given the way that method chaining works everywhere else in d3.js (i.e. the order in which methods are called doesn't seem to matter), this behavior seems a bit counter-intuitive.

**Comment by mbostock** [comment]
Yes. [Matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html) is not commutative, so the order of operations matters. The [*transform*.scale](https://github.com/d3/d3-zoom/blob/master/README.md#transform_scale) and [*transform*.translate](https://github.com/d3/d3-zoom/blob/master/README.md#transform_translate) methods are not setting “scale” and “translate” properties on the *transform* object like other D3 getter-setter methods that use method chaining, they are deriving a new transform from the current transform and returning the new transform.

**Comment by Mavromatika** [comment]
OK, thank you for your answer. I'm always lost in scaling & translation...
